Pre-training script
beekbin/bert-cosine-sim pull request #3
Opened 2019-07-28 06:56 UTC by mayurbhangale

script to download and prepare dataset for traininig

2019-07-28 14:00 UTC, beekbin commented on README.md
> +`python prerun.py` downloads, extracts and saves model and training data (STS-B) in relevant folder, after which you can simplu modify hyperparameters in `run.sh`
typo

2019-07-28 14:02 UTC, beekbin commented on README.md
> +# Preparing data for training
`Preparing data for training`  --> `Download data and pre-trained model for fine-tuning`

2019-07-28 14:02 UTC, beekbin commented on prerun.py
> +data_dir = 'data/'
It would be nicer to create two directories for data and the pre-trained model.

2019-07-28 14:06 UTC, beekbin commented on prerun.py
> +    print("\tCompleted!")
Add one line to execute the function:
 ```downloade_models()```

2019-07-28 14:10 UTC, beekbin requested changes
Hi Mayur, thanks for this PR, it will make this repo more useful.

2019-07-28 15:44 UTC, mayurbhangale commented
Updated, Please review

2019-08-11 02:44 UTC, beekbin approved these changes
Thanks a lot for your contributions!

2019-08-11 11:22 UTC, mayurbhangale commented
Please merge this to master

2019-08-12 13:55 UTC, merged